# Generated by Django 3.2.7 on 2021-09-07 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscribers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('img_url', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_date', models.DateTimeField(verbose_name='publié le ')),
                ('description', models.TextField()),
                ('book_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookViewpoints.book')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscribers.app_users')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('comment', models.TextField()),
                ('Rating', models.IntegerField(default=-1)),
                ('pub_date', models.DateTimeField(verbose_name='publié le ')),
                ('book_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookViewpoints.book')),
                ('ticket_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookViewpoints.ticket')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscribers.app_users')),
            ],
        ),
    ]
