# Generated by Django 3.2.7 on 2021-09-25 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookViewpoints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='answer',
            field=models.BooleanField(default=False),
        ),
    ]
