# Generated by Django 3.2.7 on 2021-10-04 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookViewpoints', '0002_ticket_answer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.AddField(
            model_name='ticket',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/photos/%Y/%m/%d'),
        ),
    ]
